### ISSUE TITLE
Addison tags for OPN27.76-12-22 / OPNS27.76-12-22-3

### ISSUE THREAD

**Issue by BtbN** [MotorolaMobilityLLC/motorola-external-greybus#3]
Now that the sources for the oreo addison kernel and various other parts of the system are out, I was kinda expecting this to also receive a new release.

Or did the module simply not change compared to MMI-NDN26.118-23-12?

@charleseb @chenyt9 @awheeler-mmi @hangfan1

**Comment by charleseb** [comment]
Hi @BtbN,

I'm working to release this version. We are almost there. It will be released in a couple of days.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi @BtbN,

These versions are released.

https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPNS27.76-12-22-24-3
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPN27.76-12-22

**Comment by chenyt9** [comment]
Please refer to :+1: https://github.com/MotorolaMobilityLLC/motorola-external-greybus/releases/tag/MMI-OPNS27.76-12-22-24-3
https://github.com/MotorolaMobilityLLC/motorola-external-greybus/releases/tag/MMI-OPN27.76-12-22
Thanks.
