### ISSUE TITLE
339-522-0529

### ISSUE THREAD

**Issue by smop30** [MotorolaMobilityLLC/motorola-external-greybus#5]
OPN27.76-12-22 / OPNS27.76-12-22-3

**Comment by smop30** [comment]
OPN27.76-12-22 / OPNS27.76-12-22-3

**Comment by chenyt9** [comment]
@smop30 ,
Please refer to
OPN27.76-12-22 :
https://github.com/MotorolaMobilityLLC/motorola-external-greybus/releases/tag/MMI-OPN27.76-12-22
OPNS27.76-12-22-3: 
https://github.com/MotorolaMobilityLLC/motorola-external-greybus/releases/tag/MMI-OPNS27.76-12-22-24-3
Thanks.
